name: CI RSpec Tests

on: [push, pull_request]
  push:
   paths:
   - 'api/**'
  pull_request:
    paths:
    - 'api/**'

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    env:
      api-dir: ./api 

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.1.2

      - name: Run bundle install
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Build and test with rspec
        env:
        run: bundle exec rspec spec\api_test.rb --format doc